# Generated by Django 5.0.4 on 2024-05-04 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_file_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hook_test',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
